endpoint: https://adgear.atlassian.net
authentication-method: api-token
# password-source: pass
# password-name: jira-go-token
login: dan.soucy@samsung.com
displayName: dan.soucy
api-token: HuehuTSuxetHU83dUEht
accountid: 3cf6df53cb928b0f2b3d0812
account-id: 3cf6df53cb928b0f2b3d0812
project: CM
custom-commands:

# team 59 was bananee, mobile was 85, targetting systems is 87

  - name: mine
    help: display issues assigned to me
    script: |-
     {{jira}} list --template table --query "resolution = unresolved and assignee=currentuser() ORDER BY priority asc, created"

  - name: reported
    help: display issues i reported
    script: |-
     {{jira}} list --template table --query "resolution = unresolved and reporter=currentuser() ORDER BY priority asc, created"

  - name: watching
    help: display issues i am watching
    script: |-
     {{jira}} list --template table --query "resolution = unresolved and watcher=currentuser() ORDER BY priority asc, created"

  - name: subtasks
    help: display subtasks of a task
    args:
        - name: TASK
          required: true
    script: |-
        {{jira}} list --template table --query "parent = {{args.TASK}} order by priority asc, created"

  - name: sprint
    help: display issues for active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved ORDER BY rank asc, created"
      else
          # otherwise list issues for campaign management
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved ORDER BY rank asc, created"
      fi

  - name: banana
    help: display issues for active sprint for bananee
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
      # if `project: ...` configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type not in (epic,sub-task) and Team = 87 and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
      # otherwise list issues for campaign management
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and Team = 87 and resolution = unresolved and project=CM ORDER BY rank asc, created"
      fi

  - name: grunt
    help: display items in the grunt/tech debt backlog
    script: |-
         {{jira}} list --project="AdGear System Platform"

  - name: cm
    help: display items in the campaign management backlog
    script: |-
         {{jira}} list --project=CM
